[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ApproxFun = "=0.13.28"
Bessels = "=0.2.8"
LinearAlgebra = "=1.12.0"
OrdinaryDiffEq = "=6.105.0"
Plots = "=1.41.3"
QuadGK = "=2.11.2"
SparseArrays = "=1.12.0"
SpecialFunctions = "=2.6.1"
Static = "=1.3.1"
Unitful = "=1.27.0"
julia = "~1.12"
