[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
BenchmarkTools = "=1.6.3"
Plots = "=1.41.3"
QuadGK = "=2.11.2"
SpecialFunctions = "=2.6.1"
julia = "~1.12"
