[deps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Clapeyron = "=0.6.20"
DifferentialEquations = "=7.17.0"
ForwardDiff = "=1.3.1"
NonlinearSolve = "=4.13.0"
Plots = "=1.41.3"
Roots = "=2.2.10"
Unitful = "=1.27.0"
julia = "~1.12"
