[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
GasDispersion = "ac6af613-5479-4178-853e-9d66de417193"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Contour = "=0.6.2"
GasDispersion = "=0.2.1"
LaTeXStrings = "=1.3.1"
Measures = "=0.3.2"
Plots = "=1.39.0"
julia = "~1.12"
