[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
LaTeXStrings = "=1.4.0"
Plots = "=1.41.3"
Unitful = "=1.27.0"
julia = "~1.12"
