[deps]
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
IntervalRootFinding = "=0.6.2"
Plots = "=1.41.3"
Richardson = "=1.4.2"
Roots = "=2.2.10"
julia = "~1.12"
