[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DifferentialEquations = "=7.17.0"
NBInclude = "=2.4.0"
NumericalIntegration = "=0.3.4"
Plots = "=1.41.3"
QuadGK = "=2.11.2"
StaticArrays = "=1.9.15"
julia = "~1.12"
