[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CSV = "=0.10.15"
DataFrames = "=1.8.1"
ForwardDiff = "=1.3.1"
GLMakie = "=0.13.8"
Geodesy = "=1.2.0"
SpecialFunctions = "=2.6.1"
Tyler = "=0.2.5"
Unitful = "=1.27.0"
julia = "~1.12"
