[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CSV = "=0.10.15"
DifferentialEquations = "=7.17.0"
LaTeXStrings = "=1.4.0"
NumericalIntegration = "=0.3.4"
Plots = "=1.41.3"
Roots = "=2.2.10"
StaticArrays = "=1.9.15"
julia = "~1.12"
