[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ForwardDiff = "1.3.1"
Plots = "1.41.3"
Roots = "2.2.10"
Unitful = "1.27.0"
julia = "1.12"
