[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Interpolations = "=0.16.2"
Plots = "=1.41.3"
QuadGK = "=2.11.2"
Roots = "=2.2.10"
Unitful = "=1.27.0"
julia = "~1.12"
