[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ControlSystemIdentification = "3abffc1c-5106-53b7-b354-a47bfc086282"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CSV = "=0.10.15"
ControlSystemIdentification = "=2.11.8"
ControlSystems = "=1.15.1"
DataFrames = "=1.8.1"
Dates = "=1.11.0"
DiffEqParamEstim = "=2.2.0"
Interpolations = "=0.16.2"
Optim = "=1.13.3"
OrdinaryDiffEq = "=6.105.0"
Pipe = "=1.3.0"
Plots = "=1.41.3"
julia = "~1.12"
