[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "=1.6.3"
Clapeyron = "=0.6.20"
DataInterpolations = "=8.8.0"
DiffEqCallbacks = "=4.11.0"
NaNMath = "=1.1.3"
NonlinearSolve = "=4.13.0"
OrdinaryDiffEq = "=6.105.0"
Plots = "=1.41.3"
julia = "~1.12"
