[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLOperators = "c0aeaf25-5076-4817-a8d5-81caf7dfa961"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
CairoMakie = "=0.15.8"
LinearAlgebra = "=1.12.0"
ModelingToolkit = "=11.4.0"
OrdinaryDiffEq = "=6.105.0"
Roots = "=2.2.10"
SciMLOperators = "=1.14.1"
Sundials = "=5.1.0"
Symbolics = "=7.4.1"
julia = "~1.12"
