[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Contour = "=0.6.3"
ForwardDiff = "=1.3.1"
OrdinaryDiffEq = "=6.105.0"
Plots = "=1.41.3"
Roots = "=2.2.10"
SpecialFunctions = "=2.6.1"
Statistics = "=1.11.1"
julia = "~1.12"
